---

language: python
python: "2.7"

language: ruby
rvm:
  - 2.2.0

before_install:
  - sudo apt-get update -qq
  - rvm --default use 2.2.0
  - sudo apt-get install zsh
  - ruby -v
  - sudo useradd mtester -m -d /home/mtester -s /bin/bash
  - sudo chgrp ```id -gn``` /home/mtester
  - sudo chmod g+s /home/mtester
  - sudo rm -rf /home/mtester/.zprezto*
  - sudo rm -f /home/mtester/.zlogin
  - sudo rm -f /home/mtester/.zlogout
  - sudo rm -f /home/mtester/.zpreztorc
  - sudo rm -f /home/mtester/.zprofile
  - sudo rm -f /home/mtester/.zshenv
  - umask 002
  - gem install serverspec
  - sudo pip install --upgrade pip

install:
  - sudo pip install ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
  - ansible-galaxy install -r requirements.yml -p ../ --force

script:
  # Check machine pre-test state.
  - rspec tests/spec/before_test_spec.rb

  # Check syntax
  - ansible-playbook -i tests/inventory ./tests/playbooks/main.yml --syntax-check --list-tasks

  # Check role
  - ansible-playbook -i ./tests/inventory tests/playbooks/main.yml --connection=local --sudo
  - rspec tests/spec/main_spec.rb
